POST http://localhost:3005/api/createQuestion?_id=64637adb064052c62944fdf9
content-type: application/json

{
    "Title":" the javascript question here is ",
    "Options":["a","b","c","d"],
    "Answer":"a",
    "Type":"medium"
}


###
GET http://localhost:3005/api/getQuestion
