@baseUrl=http://localhost:3005

###use camelCase convention for creating new user
POST {{baseUrl}}/user/signUp
Content-Type: application/json

{
    "userName":"vinay",
    "password":"1234567",
    "email":"vinay@gmail1.com",
    "role":"Solver",
    "phoneNumber":8930485009
}
